### ISSUE TITLE
Breaks with serde serialization panic

### ISSUE THREAD

**Issue by patrikha** [FieldofClay/hyprland-workspaces#2]
Hi,

Using hyprland-workspaces and trying to get workspace information but the command exits with error due to a serialization issue in hyprland-rs.

Sample command:

```
hyprland-workspaces DP-1
[{"active":false,"class":"workspace-button w1","id":1,"name":"1"}]
thread 'main' panicked at 'Error parsing data whith serde: expected value at line 1 column 1', /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/hyprland-0.3.3/src/event_listener/mutable.rs:53:31

```
I discussed with the hyprland-rs team but they say it works as intended.
The data that is passed back is correct but the command terminates so the eww `deflisten` will not pickup updates to the workspace layout.

Tested to rollback to hyprland-rs=0.3.2 and then it works again.

**Comment by FieldofClay** [comment]
This is very strange, we're not doing anything unique with the event listener. When I get a free moment over the next few days I'll investigate further and see what I can find.

**Comment by patrikha** [comment]
Found the issue, hyprland-rs 0.3.3 is targeted for Hyprland 0.25 (in which that changed some structures) and I'm using 0.24.
As mentioned, compiling hyprland-workspaces with 0.3.2 works as expected.
