### ISSUE TITLE
Behavior changes on Hyprland v0.42.0

### ISSUE THREAD

**Issue by julius-boettger** [FieldofClay/hyprland-workspaces#30]
### Issue Description

I just updated from Hyprland v0.41.2 to v0.42.0, and the behavior of `hyprland-workspaces _` seems to have changed.

Output before: Only workspaces that are active or have windows on them are output
```json
[{"name":"HDMI-A-1","workspaces":[{"active":true,"class":"workspace-button w1 workspace-active wa1","id":1,"name":"1"}]},{"name":"DP-1","workspaces":[{"active":false,"class":"workspace-button w11","id":11,"name":"11"}]}]
```

Output after: All (registered?) workspaces are output
```json
[{"name":"HDMI-A-1","workspaces":[{"active":true,"class":"workspace-button w1 workspace-active wa1","id":1,"name":"1"},{"active":false,"class":"workspace-button w2","id":2,"name":"2"},{"active":false,"class":"workspace-button w3","id":3,"name":"3"},{"active":false,"class":"workspace-button w4","id":4,"name":"4"},{"active":false,"class":"workspace-button w5","id":5,"name":"5"},{"active":false,"class":"workspace-button w6","id":6,"name":"6"},{"active":false,"class":"workspace-button w7","id":7,"name":"7"},{"active":false,"class":"workspace-button w8","id":8,"name":"8"},{"active":false,"class":"workspace-button w9","id":9,"name":"9"},{"active":false,"class":"workspace-button w10","id":10,"name":"10"}]},{"name":"DP-1","workspaces":[{"active":false,"class":"workspace-button w11","id":11,"name":"11"},{"active":false,"class":"workspace-button w12","id":12,"name":"12"},{"active":false,"class":"workspace-button w13","id":13,"name":"13"},"active":false,"class":"workspace-button w14","id":14,"name":"14"},{"active":false,"class":"workspace-button w15","id":15,"name":"15"},{"active":false,"class":"workspace-button w16","id":16,"name":"16"},"active":false,"class":"workspace-button w17","id":17,"name":"17"},{"active":false,"class":"workspace-button w18","id":18,"name":"18"},{"active":false,"class":"workspace-button w19","id":19,"name":"19"},"active":false,"class":"workspace-button w20","id":20,"name":"20"}]}]
```

### Expected behavior

I would like to get the same output as on v0.41.2, as my EWW config relies on determining if there are windows on a workspace through the fact that `hyprland-workspaces _` either outputs a workspace or doesn't. Alternatively, my closed PR #26, which I deemed unnecessary at the time, might actually be useful now.

### Additional notes

I also use the [split-monitor-workspaces](https://github.com/Duckonaut/split-monitor-workspaces) plugin, which could also have something to do with this...?

**Comment by FieldofClay** [comment]
Are you able to run hyprland without the plugin to see if that has an impact?

I am unable to test this myself just yet, waiting on Arch to promote 0.42 out of testing.

**Comment by julius-boettger** [comment]
Just tested it without the plugin, and everything works as expected.

The plugin, just like `hyprland-workspaces`, has not changed in the last week. Something must have changed with the new Hyprland release and how it handles some stuff internally. I would imagine that using this plugin is not the only way to encounter behavior changes with `hyprland-workspaces`, but it certainly is one of them.

My best guess is that Hyprland behaves differently when registering workspaces. If I understood the code right, the plugin seems to do this internally with `g_pCompositor->createNewWorkspace()` (see [this line](https://github.com/Duckonaut/split-monitor-workspaces/blob/7f614e3bc8f3284ebe799f741217e8ce43db9b3d/src/main.cpp#L202)). There is no [Hyprland dispatcher](https://wiki.hyprland.org/Configuring/Dispatchers/) that sounds similar, so I'm not sure how to manually reproduce this.

**Comment by FieldofClay** [comment]
I've confirmed this isn't an issue with hyprland-workspaces & hyprland 0.42. 

Looks like it was an issue with split-monitor-workspaces, see https://github.com/Duckonaut/split-monitor-workspaces/issues/116

**Comment by julius-boettger** [comment]
Oh... thank you for your efforts, I'm sorry that I seem to have misidentified the origin of this issue.
