### ISSUE TITLE
[FEATURE REQUEST] Add an option to not display any workspaces if only 1 is present

### ISSUE THREAD

**Issue by dxwil** [FieldofClay/hyprland-workspaces#31]
Hi, would it be possible to make this happen? I'd love for when there is only one workspace, for that "1" to not the visible as it's basically useless (for me at least). An option flag would be great. Thanks!

**Comment by FieldofClay** [comment]
This can be achieved by piping the output of hyprland-workspaces through jq. The following jq query will empty the workspaces array if there is only 1 workspace, otherwise will print workspaces like normal.

```
hyprland-workspaces _ | jq -rc 'map(if .workspaces | length > 1 then . else .workspaces = [] end)'
```

**Comment by dxwil** [comment]
If I run it in the command line it outputs as you'd expect, but in eww it doesn't work. Could you take a look.

```
(deflisten workspace "hyprland-workspaces _ | jq -rc 'map(if .workspaces | length > 1 then . else .workspaces = []  end)'"
)
(defwidget workspaces []
    (box :class "workspaces"
      (for i in {workspace[0].workspaces}
        (eventbox
          :onclick "hyprctl dispatch workspace ${i.id}"
          :class "${i.class}"
          "${i.name}"
))))
```

```
error: Failed to turn `` into a value of type json-value
   ┌─ /home/dxwil/.config/eww/eww.yuck:52:18
   │
52 │       (for i in {workspace[0].workspaces}
   │                  ─────────
```

**Comment by FieldofClay** [comment]
Apologises, jq needs to be told not to buffer its output for eww to handle it correctly.

```
hyprland-workspaces _ | jq -rc --unbuffered 'map(if .workspaces | length > 1 then . else .workspaces = [] end)'
```

**Comment by dxwil** [comment]
Thank you, that did it.
