### ISSUE TITLE
Package in crates.io is outdated

### ISSUE THREAD

**Issue by ju6ge** [FieldofClay/hyprland-workspaces#4]
Hey,

it seems that the crate version in crates.io is outdated. This should easily be resolved by running `cargo publish`. Otherwise running `cargo install hyprland-workspaces` will lead to an outdated version being installed locally.

Kind regards,
ju6ge

**Comment by FieldofClay** [comment]
The crates.io package is from a different repository, I never put this one up there. I will investigate getting it on crates.io, but for the meantime, just clone the repo locally and install.

**Comment by FieldofClay** [comment]
With the previous package being renamed to avoid conflicting with this one, I've now been able to upload this to crates.io. Installing directly from cargo now works. 🥳

For reference, the previously named hyprland-workspaces that conflicted is now called [hypr-helper](https://gitlab.com/hegde-atri/hypr-helper).
