### ISSUE TITLE
Hide special workspaces

### ISSUE THREAD

**Issue by xircon** [FieldofClay/hyprland-workspaces#5]
![image](https://github.com/FieldofClay/hyprland-workspaces/assets/1316691/a46b902e-704d-48f6-a7ab-5fcdfeeef02e)

I use pyprland to have pop-up terminal etc,  is it possible to hide the "negative" workspaces?  (Hyprland)

**Comment by FieldofClay** [comment]
This can be achieved by piping the output through jq:
```
hyprland-workspaces _ | jq -cM '[.[] | select(.id >= 0)]'
```

**Comment by xircon** [comment]
Where do I put it? (Thanks for the help!), this is what I ended up with - criticism extremely welcome!!!
```
;;(deflisten workspace0 "hyprland-workspaces `hyprctl monitors -j | jq -r \".[0].name\"`")

;; Only got one monitor so WTF!
(deflisten workspace0 "hyprland-workspaces eDP-1")
(deflisten workspace1 "hyprland-workspaces _ | jq -cM '[.[] | select(.id >= 0)]'")

(defwidget workspaces0 []
  (eventbox :onscroll "hyprctl dispatch workspace `echo {} | sed 's/up/+/\' | sed 's/down/-/'`1"
    (box :class "workspaces"
    	 :orientation "v"
	 :spacing 8
      (for i in workspace1
         (button
          :onclick "hyprctl dispatch workspace ${i.id}"
          :class "${i.id}" "${i.id}")))))
```
I couldn't get it to work with the first deflisten, so I abused deflisten workspace1, as I only have a laptop. EWW is hard work!  Even harder before I accidentally discovered yuck-mode (emacs) - it was just a wall of white text!!!!

**Comment by xircon** [comment]
Thanks again, works well!

**Comment by spinningvenus** [comment]
`hyprland-workspaces _ | jq -c --unbuffered '[.[] | select(.id >= 0)]'` outputs an empty array for me. I am unsure if this is related to updates in Hyprland or some idiosyncrasy of my system. 

The output of  `hyprland-workspaces _` is:
```
[{"name":"eDP-1","workspaces":[{"active":false,"class":"workspace-button w-98","id":-98,"name":"special:magic"},{"active":false,"class":"workspace-button w1","id":1,"name":"1"}]},{"name":"DP-6","workspaces":[{"active":false,"class":"workspace-button w6","id":6,"name":"6"},{"active":true,"class":"workspace-button w7 workspace-active wa7","id":7,"name":"7"},{"active":false,"class":"workspace-button w8","id":8,"name":"8"}]}]
```

I have a limited understanding of `jq`, but tried to construct a command to get the desired output:
`hyprland-workspaces _ | jq -c --unbuffered '[.[].workspaces.[] | select(.id >= 0)]'` 
This outputs 
```
[{"active":false,"class":"workspace-button w1","id":1,"name":"1"},{"active":false,"class":"workspace-button w6","id":6,"name":"6"},{"active":false,"class":"workspace-button w7","id":7,"name":"7"},{"active":true,"class":"workspace-button w8 workspace-active wa8","id":8,"name":"8"},{"active":false,"class":"workspace-button w9","id":9,"name":"9"}]
```
which doesn't work as it strips monitor information 😔 

Adding the parsing directly to program as displayed in #6 with an optional argument seems like a valid solution too, however I wanted to see how you would handle it using  `jq` as I understand your philosophy. 

Thank you.

**Comment by FieldofClay** [comment]
Sorry for the delay in getting back to you, I've been on holiday.

This is due to the fact that the behaviour of '_' changed in v2, this issue was for v1. An updated jq that works with the v2 output is:
```bash
hyprland-workspaces _ | jq -cM '[.[] | .workspaces[] | select(.id >= 0)]'
```

**Comment by spinningvenus** [comment]
Thank you so much! This works perfectly!

I hope you had a great holiday 💙
