### ISSUE TITLE
Unknown Event error when toggling hyprland's special workspace

### ISSUE THREAD

**Issue by violetcircus** [FieldofClay/hyprland-workspaces#7]
### output from hyprland-workspaces:
```
hyprland-workspaces `hyprctl monitors | grep "ID $1" | awk '{print $2}'` | jq -a -c -M 'del(.[0] | select(.name == "special"))'
[{"active":true,"class":"workspace-button w1 workspace-active wa1","id":1,"name":"1"}]
A unknown event was passed into Hyprland-rs
            PLEASE MAKE AN ISSUE!!
            The event was: activespecial
[{"active":true,"class":"workspace-button w1 workspace-active wa1","id":1,"name":"1"}]
^C
```
### to reproduce:
put this or something to its effect in your hyprland config
```
bind = $mainMod SHIFT, f, movetoworkspace,special
bind = $mainMod, f, togglespecialworkspace
```
then toggle the special workspace while running hyprland-workspaces in a terminal and watch the logs

**Comment by FieldofClay** [comment]
There is an open issue for this upstream: https://github.com/hyprland-community/hyprland-rs/issues/111

**Comment by FieldofClay** [comment]
I have updated the code base to just ignore these, instead of printing them out. So even though they haven't yet fixed this upstream, I'll close this out.
